#!/usr/bin/python

# This code has been taken from github repository https://github.com/omgimanerd/markov-music/

# This code decodes the MIDI files.
# This code has been used to check correctness of the music stored in MIDI files generated by us based on the markov chains.

import mido

def inspect(filename):
    mid = mido.MidiFile(filename)
    for i, track in enumerate(mid.tracks):
        print('Track {}: {}'.format(i, track.name))
        for message in track:
            print(message)

if __name__ == '__main__':
    import sys
    if len(sys.argv) == 2:
        inspect(sys.argv[1])
